language: c

branches:
  only:
    - crashey
    - master

compiler:
  - gcc

# migrate to travis' new container infrastructure
sudo: false

script:
  - "uname -a"
  - "bash node_build/run_jshint"
  - "./do"
  - "./android_do"
  - "SUBNODE ./do"
