[package]
name = "privatetopublic"
version = "0.1.0"
authors = ["Caleb James DeLisle <cjd@cjdns.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cjdns_sys = { path = "../cjdns_sys" }
sodiumoxide = "0.2"