[package]
name = "cjdns_sys"
version = "0.1.0"
authors = ["Caleb James DeLisle <cjd@cjdns.fr>"]
edition = "2018"
build = "build.rs"

[dependencies]
sodiumoxide = { git = "https://github.com/cjdelisle/sodiumoxide", rev = "9f6a18d40a4db253edfebac9f2ce5c22d09b1f47", version = "0.2", default-features = false, features = ["std"] }
cjdns-keys = { git = "https://github.com/CJDNS-Development-Team/CJDNS", version = "0.1.0" }
hex = "0.4"
log = "0.4"
thiserror = "1.0"
anyhow = "1.0"

[build_dependencies]
cc = "1.0"
anyhow = "1.0"
cbindgen = { version = "0.16" }
bindgen = { version = "0.55", optional = true }

[features]
generate-cffi = ["bindgen"]