[package]
name = "cjdns_sys"
version = "0.1.0"
authors = ["Caleb James DeLisle <cjd@cjdns.fr>"]
edition = "2018"
build = "build.rs"

[dependencies]
sodiumoxide = { version = "0.2", default-features = false, features = ["std"] }

[build_dependencies]
cc = "1.0"
anyhow = "1.0"
