[package]
name = "cjdns_sys"
version = "0.1.0"
authors = ["Caleb James DeLisle <cjd@cjdns.fr>"]
edition = "2018"
build = "build.rs"

[dependencies]
sodiumoxide = "0.2"

[build_dependencies]
cc = "1.0"
anyhow = "1.0"